a=int(input("Enter a number:"))
b=int(input("Enter another number:"))
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%b)
print(a<b)
print(a|b)
print(a&b)
print(a^b)
print(a is b)
print(a is not b)
list1=[1,2,3,4.5,'hi']
print(a not in list1)
print(a in list1)